# Site
name: "mirco.py"
title: "Mirco's blog"
description: "Welcome to my tech blog."
logo: 'assets/images/logo/logo_transparent.png'
favicon: 'assets/images/logo/favicon.png'
baseurl: '/blog'
google_analytics: 'UA-135354838-1'
disqus: 'mircopp'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: mirco.pyrtek@gmail.com
formspree: xrgjbpry

# Authors
authors:
  mirco:
    name: Mirco
    display_name: Mirco
    avatar: 'assets/images/mirco.jpg'
    email: mirco.pyrte@gmail.com
    web: https://github.com/mircopp
    twitter: https://twitter.com/mircopp1
    github: https://github.com/mircopp
    description: "Main blog author, tech enthusiast and professional data engineer at CentralNic PLC."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
